# Generated by Django 4.2.30 on 2026-08-18 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roster', '0013_incidenciaturno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.CharField(help_text='Código único del equipo (Ej: EQ-01)', max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del equipo', max_length=150)),
                ('tipo', models.CharField(default='EQUIPO', help_text='Tipo o categoría del equipo', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Disponibilidad operativa en planta')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInsumo',
            fields=[
                ('id', models.CharField(help_text='Código único del material (Ej: MAT-01)', max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del material o insumo', max_length=150)),
                ('stock_controlado', models.BooleanField(default=True, help_text='Indica si requiere control estricto de lote')),
                ('activo', models.BooleanField(default=True, help_text='Disponible para uso en recetas')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_codigo', models.CharField(help_text='Código del lote de producción asociado (Ej: LOTE-CHO-01)', max_length=100)),
                ('titulo', models.CharField(help_text='Nombre de la actividad operativa', max_length=200)),
                ('fecha', models.DateField(help_text='Fecha programada para la ejecución (YYYY-MM-DD)')),
                ('hora_inicio', models.TimeField(help_text='Hora estimada de inicio')),
                ('hora_fin', models.TimeField(help_text='Hora estimada de finalización')),
                ('turno_req', models.CharField(choices=[('M', 'Matutino'), ('T', 'Vespertino'), ('N', 'Nocturno'), ('OFF', 'Descanso')], default='M', help_text='Turno requerido para la tarea', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipos', models.ManyToManyField(blank=True, related_name='actividades', to='actividades.equipo')),
                ('materiales', models.ManyToManyField(blank=True, related_name='actividades', to='actividades.materialinsumo')),
                ('operador_asignado', models.ForeignKey(blank=True, help_text='Operador responsable asignado desde el Roster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_semanales', to='roster.operador')),
            ],
        ),
    ]
