# Generated by Django 4.2.30 on 2026-08-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0014_tipoturno_hora_fin_tipoturno_hora_inicio'),
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadsemanal',
            name='operador_asignado',
        ),
        migrations.AddField(
            model_name='actividadsemanal',
            name='operadores_asignados',
            field=models.ManyToManyField(blank=True, help_text='Operadores responsables asignados desde el Roster', related_name='actividades_semanales', to='roster.operador'),
        ),
        migrations.AddField(
            model_name='actividadsemanal',
            name='personal_requerido',
            field=models.PositiveIntegerField(default=1, help_text='Número mínimo de operadores necesarios'),
        ),
    ]
