# Generated by Django 4.2.30 on 2026-07-30 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ej: A, B, C', max_length=5, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la cuadrilla', max_length=100)),
                ('activa', models.BooleanField(default=True, help_text='Define si la cuadrilla está operando actualmente')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuadrilla',
                'verbose_name_plural': 'Cuadrillas',
                'ordering': ['identificador'],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operadores', to='roster.cuadrilla')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['cuadrilla__identificador', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TurnoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('codigo_turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('TR', 'Turno Rotativo'), ('OFF', 'Descanso'), ('F', 'Falta'), ('INC', 'Incapacidad'), ('--', 'Sin Rol')], default='--', max_length=5)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='roster.operador')),
            ],
            options={
                'verbose_name': 'Turno Diario',
                'verbose_name_plural': 'Turnos Diarios',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='turnodia',
            constraint=models.UniqueConstraint(fields=('operador', 'fecha'), name='unique_turno_operador_fecha'),
        ),
    ]
