# Generated by Django 4.2.30 on 2026-08-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True, verbose_name='Identificador de Cuadrilla')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Descriptivo')),
                ('activa', models.BooleanField(default=True, verbose_name='Cuadrilla Activa')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Área')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Cuadrilla',
                'verbose_name_plural': 'Cuadrillas',
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Operador')),
                ('codigo_empleado', models.CharField(max_length=50, unique=True, verbose_name='Código de Empleado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo en Operación')),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='roster.cuadrilla', verbose_name='Cuadrilla Asignada')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
            },
        ),
        migrations.CreateModel(
            name='TurnoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Asignación')),
                ('codigo_turno', models.CharField(choices=[('M', 'Matutino'), ('T', 'Vespertino'), ('N', 'Nocturno'), ('TR', 'Turno Rotativo / Transición'), ('OFF', 'Descanso'), ('F', 'Falta'), ('INC', 'Incapacidad')], max_length=10, verbose_name='Código de Turno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización (GxP)')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='roster.operador', verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Asignación de Turno',
                'verbose_name_plural': 'Asignaciones de Turnos',
                'unique_together': {('operador', 'fecha')},
            },
        ),
    ]
