# Generated by Django 4.2.30 on 2026-08-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='codigo_empleado',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Empleado'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='codigo_turno',
            field=models.CharField(choices=[('M', 'Matutino'), ('T', 'Vespertino'), ('N', 'Nocturno'), ('TR', 'Turno Rotativo / Transición'), ('OFF', 'Descanso'), ('F', 'Falta'), ('INC', 'Incapacidad'), ('--', 'Sin Asignación / Inactivo')], max_length=10, verbose_name='Código de Turno'),
        ),
    ]
