# Generated by Django 4.2.30 on 2026-08-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_alter_operador_codigo_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='operadores/fotos/', verbose_name='Fotografía del Colaborador'),
        ),
        migrations.AddField(
            model_name='operador',
            name='nivel_expertiz',
            field=models.CharField(choices=[('JUNIOR', 'Operador Junior'), ('SENIOR', 'Operador Senior'), ('ESPECIALISTA', 'Especialista Upstream')], default='JUNIOR', max_length=30, verbose_name='Nivel de Expertiz'),
        ),
    ]
