# Generated by Django 4.2.30 on 2026-08-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_operador_foto_operador_nivel_expertiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Patrón')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Descriptivo')),
                ('secuencia', models.JSONField(help_text="Ejemplo: ['M', 'T', 'OFF', 'OFF']", verbose_name='Secuencia de Turnos (JSON)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Patrón de Turno',
                'verbose_name_plural': 'Patrones de Turnos',
            },
        ),
    ]
