# Generated by Django 5.1 on 2026-08-05 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_patronturno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='roster.cuadrilla', verbose_name='Cuadrilla Asignada'),
        ),
    ]
