# Generated by Django 5.1 on 2026-08-06 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_alter_operador_cuadrilla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatronTurno',
        ),
        migrations.AlterField(
            model_name='operador',
            name='cuadrilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='roster.cuadrilla', verbose_name='Cuadrilla Asignada'),
        ),
    ]
