# Generated by Django 4.2.30 on 2026-08-07 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_delete_patronturno_alter_operador_cuadrilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: PATRON_5X2', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('secuencia', models.JSONField(help_text="Lista ordenada de códigos de turno, Ej: ['M', 'M', 'T', 'T', 'OFF', 'OFF']")),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Patrón de Turno',
                'verbose_name_plural': 'Patrones de Turno',
            },
        ),
        migrations.CreateModel(
            name='TurnoOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del turno operacional (YYYY-MM-DD)')),
                ('codigo_turno', models.CharField(choices=[('--', 'Sin Asignar'), ('M', 'Matutino'), ('T', 'Vespertino'), ('N', 'Nocturno'), ('TR', 'Turno Regular / Especial'), ('OFF', 'Descanso'), ('INC', 'Incapacidad'), ('F', 'Falta / Permiso')], default='--', max_length=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Turno de Operador',
                'verbose_name_plural': 'Turnos de Operadores',
            },
        ),
        migrations.AlterModelOptions(
            name='cuadrilla',
            options={'ordering': ['identificador'], 'verbose_name': 'Cuadrilla', 'verbose_name_plural': 'Cuadrillas'},
        ),
        migrations.AlterModelOptions(
            name='operador',
            options={'ordering': ['nombre'], 'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.RemoveField(
            model_name='cuadrilla',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cuadrilla',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='nivel_expertiz',
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operador',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='identificador',
            field=models.CharField(help_text='Ej: A, B, C, D', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='nombre',
            field=models.CharField(help_text='Ej: Cuadrilla Alpha Upstream', max_length=100),
        ),
        migrations.AlterField(
            model_name='operador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='codigo_empleado',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, help_text='Cuadrilla a la que pertenece actualmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores', to='roster.cuadrilla'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='foto',
            field=models.ImageField(blank=True, help_text='Avatar o fotografía oficial', null=True, upload_to='operadores_fotos/'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del operador', max_length=150),
        ),
        migrations.DeleteModel(
            name='TurnoDia',
        ),
        migrations.AddField(
            model_name='turnooperador',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='roster.operador'),
        ),
        migrations.AddIndex(
            model_name='turnooperador',
            index=models.Index(fields=['fecha', 'operador'], name='roster_turn_fecha_e7135b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='turnooperador',
            unique_together={('operador', 'fecha')},
        ),
    ]
