# Generated by Django 4.2.30 on 2026-08-10 22:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_patronturno_turnooperador_alter_cuadrilla_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Asignación')),
                ('codigo_turno', models.CharField(choices=[('M', 'Matutino'), ('T', 'Vespertino'), ('N', 'Nocturno'), ('TR', 'Turno Rotativo / Transición'), ('OFF', 'Descanso'), ('F', 'Falta'), ('INC', 'Incapacidad'), ('--', 'Sin Asignación / Inactivo')], max_length=10, verbose_name='Código de Turno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización (GxP)')),
            ],
            options={
                'verbose_name': 'Asignación de Turno',
                'verbose_name_plural': 'Asignaciones de Turnos',
            },
        ),
        migrations.DeleteModel(
            name='PatronTurno',
        ),
        migrations.AlterModelOptions(
            name='cuadrilla',
            options={'verbose_name': 'Cuadrilla', 'verbose_name_plural': 'Cuadrillas'},
        ),
        migrations.AlterModelOptions(
            name='operador',
            options={'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.RemoveField(
            model_name='cuadrilla',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='cuadrilla',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Área'),
        ),
        migrations.AddField(
            model_name='operador',
            name='nivel_expertiz',
            field=models.CharField(choices=[('JUNIOR', 'Operador Junior'), ('SENIOR', 'Operador Senior'), ('ESPECIALISTA', 'Especialista Upstream')], default='JUNIOR', max_length=30, verbose_name='Nivel de Expertiz'),
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Cuadrilla Activa'),
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='identificador',
            field=models.CharField(max_length=50, unique=True, verbose_name='Identificador de Cuadrilla'),
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Descriptivo'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo en Operación'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='codigo_empleado',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Empleado'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='cuadrilla',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='roster.cuadrilla', verbose_name='Cuadrilla Asignada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='operadores/fotos/', verbose_name='Fotografía del Colaborador'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del Operador'),
        ),
        migrations.DeleteModel(
            name='TurnoOperador',
        ),
        migrations.AddField(
            model_name='turnodia',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='roster.operador', verbose_name='Operador'),
        ),
        migrations.AlterUniqueTogether(
            name='turnodia',
            unique_together={('operador', 'fecha')},
        ),
    ]
