# Generated by Django 4.2.30 on 2026-08-10 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_turnodia_delete_patronturno_alter_cuadrilla_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Secuencia')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Está Activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Secuencia de Rol',
                'verbose_name_plural': 'Secuencias de Rol',
            },
        ),
        migrations.CreateModel(
            name='SecuenciaRolDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(verbose_name='Orden de Ejecución')),
                ('codigo_turno', models.CharField(choices=[('M', 'Matutino'), ('T', 'Vespertino'), ('N', 'Nocturno'), ('TR', 'Turno Rotativo / Transición'), ('OFF', 'Descanso'), ('F', 'Falta'), ('INC', 'Incapacidad'), ('--', 'Sin Asignación / Inactivo')], max_length=10, verbose_name='Código de Turno')),
                ('dias', models.PositiveIntegerField(verbose_name='Cantidad de Días')),
                ('secuencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='roster.secuenciarol', verbose_name='Secuencia Padre')),
            ],
            options={
                'verbose_name': 'Detalle de Secuencia',
                'verbose_name_plural': 'Detalles de Secuencia',
                'ordering': ['orden'],
            },
        ),
    ]
