# Generated by Django 4.2.30 on 2026-08-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_secuenciarol_secuenciaroldetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuadrilla',
            options={'ordering': ['identificador'], 'verbose_name': 'Cuadrilla', 'verbose_name_plural': 'Cuadrillas'},
        ),
        migrations.AlterModelOptions(
            name='operador',
            options={'ordering': ['codigo_empleado'], 'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.AlterModelOptions(
            name='secuenciarol',
            options={'ordering': ['nombre'], 'verbose_name': 'Secuencia de Rol', 'verbose_name_plural': 'Secuencias de Rol'},
        ),
        migrations.AlterModelOptions(
            name='secuenciaroldetalle',
            options={'ordering': ['secuencia', 'orden'], 'verbose_name': 'Detalle de Secuencia', 'verbose_name_plural': 'Detalles de Secuencia'},
        ),
        migrations.AlterModelOptions(
            name='turnodia',
            options={'ordering': ['-fecha', 'operador'], 'verbose_name': 'Asignación de Turno', 'verbose_name_plural': 'Asignaciones de Turnos'},
        ),
        migrations.AlterField(
            model_name='secuenciarol',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Secuencia'),
        ),
        migrations.AlterField(
            model_name='secuenciaroldetalle',
            name='codigo_turno',
            field=models.CharField(choices=[('M', 'Matutino'), ('T', 'Vespertino'), ('N', 'Nocturno'), ('TR', 'Turno Rotativo / Transición'), ('OFF', 'Descanso'), ('F', 'Falta'), ('INC', 'Incapacidad'), ('--', 'Sin Asignación / Inactivo'), ('', 'Sin Asignación / Inactivo')], max_length=10, verbose_name='Código de Turno'),
        ),
        migrations.AlterField(
            model_name='secuenciaroldetalle',
            name='dias',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de Días'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='codigo_turno',
            field=models.CharField(choices=[('M', 'Matutino'), ('T', 'Vespertino'), ('N', 'Nocturno'), ('TR', 'Turno Rotativo / Transición'), ('OFF', 'Descanso'), ('F', 'Falta'), ('INC', 'Incapacidad'), ('--', 'Sin Asignación / Inactivo'), ('', 'Sin Asignación / Inactivo')], default='', max_length=10, verbose_name='Código de Turno'),
        ),
    ]
