# Generated by Django 4.2.30 on 2026-08-14 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_alter_cuadrilla_options_alter_operador_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuadrilla',
            old_name='created_at',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='secuenciarol',
            old_name='created_at',
            new_name='creado_en',
        ),
        migrations.RemoveField(
            model_name='turnodia',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='operador',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='operador',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secuenciarol',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='secuenciaroldetalle',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='secuenciaroldetalle',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnodia',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='turnodia',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
    ]
