# Generated by Django 4.2.30 on 2026-08-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_rename_created_at_cuadrilla_creado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTurno',
            fields=[
                ('codigo', models.CharField(help_text='Identificador corto único (ej. M, T, N, PERF)', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Código de Turno')),
                ('nombre', models.CharField(help_text='Descripción larga del turno (ej. Mañana, Perfusión Especial)', max_length=100, verbose_name='Nombre Descriptivo')),
                ('color_fondo', models.CharField(default='#3b82f6', help_text='Código HEX para el fondo de la celda (ej. #3b82f6)', max_length=7, verbose_name='Color de Fondo (HEX)')),
                ('color_texto', models.CharField(default='#ffffff', help_text='Código HEX para el texto de la celda (ej. #ffffff)', max_length=7, verbose_name='Color de Texto (HEX)')),
                ('es_descanso', models.BooleanField(default=False, help_text='Marca si el turno representa tiempo libre o ausencia no operativa', verbose_name='¿Es Descanso?')),
                ('activo', models.BooleanField(default=True, help_text='Baja lógica para preservar la trazabilidad histórica GxP', verbose_name='Turno Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Turno',
                'verbose_name_plural': 'Tipos de Turnos',
                'ordering': ['codigo'],
            },
        ),
        migrations.RemoveField(
            model_name='secuenciaroldetalle',
            name='codigo_turno',
        ),
        migrations.RemoveField(
            model_name='turnodia',
            name='codigo_turno',
        ),
        migrations.AddField(
            model_name='secuenciaroldetalle',
            name='tipo_turno',
            field=models.ForeignKey(db_column='codigo_turno', default='M', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_secuencia', to='roster.tipoturno', verbose_name='Tipo de Turno'),
        ),
        migrations.AddField(
            model_name='turnodia',
            name='tipo_turno',
            field=models.ForeignKey(db_column='codigo_turno', default='M', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='roster.tipoturno', verbose_name='Tipo de Turno'),
        ),
    ]
