# Generated by Django 4.2.30 on 2026-08-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0012_tipoturno_remove_secuenciaroldetalle_codigo_turno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_retardo', models.PositiveIntegerField(blank=True, help_text='Tiempo de llegada tardía en minutos.', null=True, verbose_name='Minutos de Retardo')),
                ('horas_salida_anticipada', models.DecimalField(blank=True, decimal_places=2, help_text='Ejemplo: 1.5 para hora y media.', max_digits=4, null=True, verbose_name='Horas de Salida Anticipada')),
                ('notas', models.TextField(blank=True, help_text='Justificación o anotación general sobre el evento.', null=True, verbose_name='Notas u Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('turno_dia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incidencia', to='roster.turnodia', verbose_name='Turno Asignado')),
            ],
            options={
                'verbose_name': 'Incidencia de Turno',
                'verbose_name_plural': 'Incidencias de Turnos',
            },
        ),
        migrations.AddConstraint(
            model_name='incidenciaturno',
            constraint=models.CheckConstraint(check=models.Q(('minutos_retardo__isnull', False), ('horas_salida_anticipada__isnull', False), models.Q(models.Q(('notas__exact', ''), _negated=True), ('notas__isnull', False)), _connector='OR'), name='check_incidencia_requiere_datos'),
        ),
    ]
