# Generated by Django 4.2.30 on 2026-08-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0013_incidenciaturno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoturno',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Hora oficial de salida para el turno (Formato HH:MM)', null=True, verbose_name='Hora de Fin'),
        ),
        migrations.AddField(
            model_name='tipoturno',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Hora oficial de entrada para el turno (Formato HH:MM)', null=True, verbose_name='Hora de Inicio'),
        ),
    ]
