# Generated by Django 4.2.30 on 2026-08-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0014_tipoturno_hora_fin_tipoturno_hora_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Rol / Nivel')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de Competencias')),
                ('activo', models.BooleanField(default=True, help_text='Baja lógica', verbose_name='Rol Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol Operacional',
                'verbose_name_plural': 'Roles Operacionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='operador',
            name='nivel_expertiz',
        ),
        migrations.AddField(
            model_name='operador',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operadores', to='roster.roloperador', verbose_name='Rol / Nivel de Expertiz'),
        ),
    ]
