# Generated by Django 4.2.30 on 2026-09-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0015_roloperador_remove_operador_nivel_expertiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='pin_acceso',
            field=models.CharField(blank=True, help_text='Código numérico (4-6 dígitos) para la firma electrónica en la Tablet.', max_length=6, null=True, verbose_name='PIN GxP (eBR)'),
        ),
        migrations.AlterField(
            model_name='incidenciaturno',
            name='horas_salida_anticipada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Horas de Salida Anticipada'),
        ),
        migrations.AlterField(
            model_name='incidenciaturno',
            name='minutos_retardo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minutos de Retardo'),
        ),
        migrations.AlterField(
            model_name='incidenciaturno',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas u Observaciones'),
        ),
    ]
