# Generated by Django 4.2.30 on 2026-08-19 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0002_remove_actividadsemanal_operador_asignado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del bioproceso / Protocolo (Ej: Fermentación Fed-Batch)', max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción técnica de la receta', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Disponible para instanciación en lotes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_paso', models.CharField(help_text='Identificador único del paso (Ej: T1, T2)', max_length=20)),
                ('nombre', models.CharField(help_text='Nombre de la operación o fase', max_length=200)),
                ('tipo_operacion', models.CharField(choices=[('ACTIVA', '⚙️ Activa (Operador en planta)'), ('INCUBACION', '🧫 Incubación / Biomasa (Pasiva)')], default='ACTIVA', max_length=20)),
                ('duracion_horas', models.FloatField(help_text='Duración estimada en horas')),
                ('frecuencia_muestreo_horas', models.PositiveIntegerField(default=0, help_text='Frecuencia de muestreo cíclico en horas (0 si no aplica)')),
                ('personal_requerido', models.PositiveIntegerField(default=1, help_text='Número de operadores requeridos para la actividad')),
                ('tipo_equipo_requerido', models.CharField(default='N/A', help_text='Categoría o tipo de equipo requerido (Ej: Biorreactor, Autoclave, Centrífuga)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materiales_requeridos', models.ManyToManyField(blank=True, help_text='Insumos o materiales consumibles necesarios para la fase', related_name='operaciones_proceso', to='actividades.materialinsumo')),
                ('predecesora', models.ForeignKey(blank=True, help_text='Operación predecesora inmediata en la ruta crítica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucesoras', to='procesos.operacionproceso')),
                ('proceso', models.ForeignKey(help_text='Proceso maestro al que pertenece esta operación', on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='procesos.procesomaestro')),
            ],
        ),
    ]
