# Generated by Django 4.2.30 on 2026-08-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionproceso',
            name='desfase_horas',
            field=models.FloatField(default=0, help_text='Holgura o anticipación en horas respecto a la predecesora (Ej: -24 para 1 día antes)'),
        ),
        migrations.AddField(
            model_name='operacionproceso',
            name='tipo_dependencia',
            field=models.CharField(choices=[('FS', 'Fin a Inicio (Finish-to-Start)'), ('SS', 'Inicio a Inicio (Start-to-Start)'), ('OFFSET', 'Desfase Temporal Fijo (Offset de Calendario)')], default='FS', help_text='Regla lógica de dependencia', max_length=10),
        ),
    ]
