# Generated by Django 4.2.30 on 2026-08-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0002_operacionproceso_desfase_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionproceso',
            name='duracion_muestreo_horas',
            field=models.FloatField(default=0.0, help_text='Duración en horas de cada evento de muestreo'),
        ),
        migrations.AddField(
            model_name='operacionproceso',
            name='ops_muestreo',
            field=models.PositiveIntegerField(default=1, help_text='Número de operadores requeridos para cada muestreo cíclico'),
        ),
    ]
