# Generated by Django 4.2.30 on 2026-08-20 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0015_roloperador_remove_operador_nivel_expertiz_and_more'),
        ('procesos', '0003_operacionproceso_duracion_muestreo_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionproceso',
            name='ops_muestreo',
            field=models.PositiveIntegerField(default=1, help_text='Número total de operadores requeridos para cada muestreo'),
        ),
        migrations.AlterField(
            model_name='operacionproceso',
            name='personal_requerido',
            field=models.PositiveIntegerField(default=1, help_text='Número total de operadores requeridos (Se migrará a requerimientos específicos por rol)'),
        ),
        migrations.CreateModel(
            name='RequerimientoPersonalFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de operadores con este rol que deben ser asignados')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos_rol', to='procesos.operacionproceso', verbose_name='Operación / Fase CPM')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requerido_en_operaciones', to='roster.roloperador', verbose_name='Rol / Competencia Requerida')),
            ],
            options={
                'verbose_name': 'Requerimiento de Personal',
                'verbose_name_plural': 'Requerimientos de Personal',
                'unique_together': {('operacion', 'rol')},
            },
        ),
    ]
