# Generated by Django 4.2.30 on 2026-08-20 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0015_roloperador_remove_operador_nivel_expertiz_and_more'),
        ('procesos', '0004_alter_operacionproceso_ops_muestreo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_lote', models.CharField(help_text='ID oficial del Lote (Ej: LOTE-EPO-2026X)', max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('PLANEADO', 'Planeado'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('DESVIACION', 'Desviación / Detenido')], default='PLANEADO', max_length=20)),
                ('fecha_inicio_planeada', models.DateField(help_text='Fecha estimada o programada de inicio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proceso_maestro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lotes_instanciados', to='procesos.procesomaestro')),
            ],
            options={
                'verbose_name': 'Lote de Producción',
                'verbose_name_plural': 'Lotes de Producción',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaseLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('OMITIDA', 'Omitida / Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_inicio_real', models.DateTimeField(blank=True, help_text='Timestamp real de inicio de la tarea', null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, help_text='Timestamp real de fin de la tarea', null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='procesos.loteproduccion')),
                ('operacion_maestra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fases_ejecutadas', to='procesos.operacionproceso')),
            ],
            options={
                'verbose_name': 'Fase de Lote',
                'verbose_name_plural': 'Fases de Lote',
                'ordering': ['operacion_maestra__identificador_paso'],
                'unique_together': {('lote', 'operacion_maestra')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionFaseOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_invertidas', models.FloatField(default=0.0, help_text='Horas reales registradas por el operador en esta fase')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('fase_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores_asignados', to='procesos.faselote')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fases_lote_ejecutadas', to='roster.operador')),
                ('rol_ejercido', models.ForeignKey(help_text='La competencia bajo la cual se asignó al operador a esta tarea', on_delete=django.db.models.deletion.RESTRICT, to='roster.roloperador')),
            ],
            options={
                'verbose_name': 'Asignación de Operador a Fase',
                'verbose_name_plural': 'Asignaciones de Operadores a Fases',
                'unique_together': {('fase_lote', 'operador')},
            },
        ),
    ]
