# Generated by Django 4.2.30 on 2026-08-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0005_loteproduccion_faselote_asignacionfaseoperador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteproduccion',
            name='fecha_inicio_planeada',
            field=models.DateTimeField(help_text='Fecha y hora estimada o programada de inicio'),
        ),
    ]
