# Generated by Django 4.2.30 on 2026-08-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_remove_actividadsemanal_operador_asignado_and_more'),
        ('procesos', '0006_alter_loteproduccion_fecha_inicio_planeada'),
    ]

    operations = [
        migrations.AddField(
            model_name='faselote',
            name='equipos_asignados',
            field=models.ManyToManyField(blank=True, help_text='Equipos reservados/asignados a esta fase', related_name='fases_asignadas', to='actividades.equipo'),
        ),
        migrations.AddField(
            model_name='faselote',
            name='fecha_programada',
            field=models.DateField(blank=True, help_text='Fecha calculada por el algoritmo para su ejecución', null=True),
        ),
        migrations.AddField(
            model_name='faselote',
            name='hora_fin_programada',
            field=models.TimeField(blank=True, help_text='Hora calculada de finalización', null=True),
        ),
        migrations.AddField(
            model_name='faselote',
            name='hora_inicio_programada',
            field=models.TimeField(blank=True, help_text='Hora calculada de inicio', null=True),
        ),
        migrations.AddField(
            model_name='faselote',
            name='materiales_asignados',
            field=models.ManyToManyField(blank=True, help_text='Materiales o lotes de insumos asignados a esta fase', related_name='fases_asignadas', to='actividades.materialinsumo'),
        ),
    ]
