# Generated by Django 4.2.30 on 2026-08-27 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0007_faselote_equipos_asignados_faselote_fecha_programada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la Etapa (Ej: Fase 1 - Expansión Celular)', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de secuencia lógica para visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proceso', models.ForeignKey(help_text='Proceso maestro al que pertenece esta etapa', on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='procesos.procesomaestro')),
            ],
            options={
                'verbose_name': 'Etapa de Proceso',
                'verbose_name_plural': 'Etapas de Procesos',
                'ordering': ['proceso', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='operacionproceso',
            name='etapa',
            field=models.ForeignKey(blank=True, help_text='Etapa lógica a la que pertenece esta actividad (Opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones', to='procesos.etapaproceso'),
        ),
    ]
