# Generated by Django 4.2.30 on 2026-09-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0008_etapaproceso_operacionproceso_etapa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faselote',
            options={'ordering': ['operacion_maestra__identificador_paso', 'indice_muestreo'], 'verbose_name': 'Fase de Lote', 'verbose_name_plural': 'Fases de Lote'},
        ),
        migrations.AlterUniqueTogether(
            name='faselote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='faselote',
            name='es_subtarea_muestreo',
            field=models.BooleanField(default=False, help_text='Indica si esta fase es un evento de muestreo derivado de una incubación'),
        ),
        migrations.AddField(
            model_name='faselote',
            name='indice_muestreo',
            field=models.PositiveIntegerField(default=0, help_text='Secuencia del muestreo (Ej: 1, 2, 3...)'),
        ),
        migrations.AddField(
            model_name='faselote',
            name='nombre_tarea_dinamica',
            field=models.CharField(blank=True, help_text='Sobreescribe el nombre original (Ej: Toma de Muestra #1 - Inoculación)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operacionproceso',
            name='personal_requerido',
            field=models.PositiveIntegerField(default=1, help_text='Número total de operadores requeridos'),
        ),
    ]
