# Generated by Django 4.2.30 on 2026-09-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0009_alter_faselote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faselote',
            name='fecha_base_cpm',
            field=models.DateField(blank=True, help_text='Fecha original dictada por el algoritmo CPM (Inmutable)', null=True),
        ),
        migrations.AddField(
            model_name='faselote',
            name='hora_fin_base_cpm',
            field=models.TimeField(blank=True, help_text='Hora original de fin CPM (Inmutable)', null=True),
        ),
        migrations.AddField(
            model_name='faselote',
            name='hora_inicio_base_cpm',
            field=models.TimeField(blank=True, help_text='Hora original de inicio CPM (Inmutable)', null=True),
        ),
        migrations.AddField(
            model_name='faselote',
            name='motivo_reprogramacion',
            field=models.CharField(blank=True, choices=[('MANTENIMIENTO', '⚙️ Mantenimiento de Equipo'), ('INSUMOS', '📦 Falta / Retraso de Insumos'), ('PERSONAL', '👥 Ausentismo / Falta de Personal'), ('CALIDAD', '🔬 Desviación de Calidad previa'), ('PRODUCCION', '⏳ Retraso acumulado en producción'), ('OTRO', '📝 Otro (Especificar en notas)')], help_text='Razón estandarizada del cambio de fecha', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faselote',
            name='notas_reprogramacion',
            field=models.TextField(blank=True, help_text='Justificación detallada del retraso o reprogramación', null=True),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='fecha_programada',
            field=models.DateField(blank=True, help_text='Fecha actual programada (Forecast)', null=True),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='hora_fin_programada',
            field=models.TimeField(blank=True, help_text='Hora actual de finalización (Forecast)', null=True),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='hora_inicio_programada',
            field=models.TimeField(blank=True, help_text='Hora actual de inicio (Forecast)', null=True),
        ),
    ]
