# Generated by Django 4.2.30 on 2026-09-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0010_faselote_fecha_base_cpm_faselote_hora_fin_base_cpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproduccion',
            name='archivado',
            field=models.BooleanField(default=False, help_text='Oculta el lote de los tableros activos (Soft Delete)'),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='motivo_aborto',
            field=models.TextField(blank=True, help_text='Justificación documentada GxP si el lote se aborta', null=True),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='estado',
            field=models.CharField(choices=[('PLANEADO', 'Planeado'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('DESVIACION', 'Desviación / Detenido'), ('ABORTADO', 'Abortado / Cancelado')], default='PLANEADO', max_length=20),
        ),
    ]
