# Generated by Django 4.2.30 on 2026-09-18 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_remove_actividadsemanal_operador_asignado_and_more'),
        ('roster', '0015_roloperador_remove_operador_nivel_expertiz_and_more'),
        ('procesos', '0011_loteproduccion_archivado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operacionproceso',
            options={'ordering': ['proceso', 'orden', 'id'], 'verbose_name': 'Operación de Proceso', 'verbose_name_plural': 'Operaciones de Procesos'},
        ),
        migrations.AddField(
            model_name='operacionproceso',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de secuencia visual y lógica de la actividad'),
        ),
        migrations.AlterField(
            model_name='asignacionfaseoperador',
            name='horas_invertidas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='asignacionfaseoperador',
            name='rol_ejercido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='roster.roloperador'),
        ),
        migrations.AlterField(
            model_name='etapaproceso',
            name='nombre',
            field=models.CharField(help_text='Nombre de la Etapa', max_length=200),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='equipos_asignados',
            field=models.ManyToManyField(blank=True, related_name='fases_asignadas', to='actividades.equipo'),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='es_subtarea_muestreo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='fecha_base_cpm',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='fecha_fin_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='fecha_inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='hora_fin_base_cpm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='hora_fin_programada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='hora_inicio_base_cpm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='hora_inicio_programada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='indice_muestreo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='materiales_asignados',
            field=models.ManyToManyField(blank=True, related_name='fases_asignadas', to='actividades.materialinsumo'),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='motivo_reprogramacion',
            field=models.CharField(blank=True, choices=[('MANTENIMIENTO', '⚙️ Mantenimiento de Equipo'), ('INSUMOS', '📦 Falta / Retraso de Insumos'), ('PERSONAL', '👥 Ausentismo / Falta de Personal'), ('CALIDAD', '🔬 Desviación de Calidad previa'), ('PRODUCCION', '⏳ Retraso acumulado en producción'), ('OTRO', '📝 Otro (Especificar en notas)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='nombre_tarea_dinamica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faselote',
            name='notas_reprogramacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='fecha_inicio_planeada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='identificador_lote',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='motivo_aborto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operacionproceso',
            name='desfase_horas',
            field=models.FloatField(default=0, help_text='Holgura o anticipación en horas respecto a la predecesora'),
        ),
        migrations.AlterField(
            model_name='operacionproceso',
            name='frecuencia_muestreo_horas',
            field=models.PositiveIntegerField(default=0, help_text='Frecuencia de muestreo cíclico en horas'),
        ),
        migrations.AlterField(
            model_name='operacionproceso',
            name='materiales_requeridos',
            field=models.ManyToManyField(blank=True, help_text='Insumos o materiales consumibles necesarios', related_name='operaciones_proceso', to='actividades.materialinsumo'),
        ),
        migrations.AlterField(
            model_name='operacionproceso',
            name='tipo_equipo_requerido',
            field=models.CharField(default='N/A', help_text='Categoría o tipo de equipo requerido', max_length=100),
        ),
        migrations.AlterField(
            model_name='requerimientopersonalfase',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
