# Generated by Django 4.2.30 on 2026-09-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0012_alter_operacionproceso_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='operacionproceso',
            constraint=models.UniqueConstraint(fields=('proceso', 'identificador_paso'), name='unique_paso_per_proceso'),
        ),
    ]
